**NUMPY**

In [3]:
import numpy as np

In [5]:
list=[1,2,3,4]
arr=np.array(list)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [20]:
arr.shape
arr.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [26]:
list1=[1,2]
list2=[4,545]
list3=[7,82]
arr=np.array([list1,list2,list3])

In [28]:
arr
arr.reshape(2,3)

array([[  1,   2,   4],
       [545,   7,  82]])

In [29]:
arr=arr.reshape(1,6)

In [30]:
arr[0]

array([  1,   2,   4, 545,   7,  82])

In [31]:
arr.reshape(6,)

array([  1,   2,   4, 545,   7,  82])

In [32]:
arr[0]

array([  1,   2,   4, 545,   7,  82])

In [33]:
arr[0][0]

np.int64(1)