**NUMPY**

In [1]:
import numpy as np

In [2]:
list=[1,2,3,4]
arr=np.array(list)

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape
arr.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [6]:
list1=[1,2]
list2=[4,545]
list3=[7,82]
arr=np.array([list1,list2,list3])

In [7]:
arr
arr.reshape(2,3)

array([[  1,   2,   4],
       [545,   7,  82]])

In [8]:
arr=arr.reshape(1,6)

In [9]:
arr[0]

array([  1,   2,   4, 545,   7,  82])

In [10]:
arr.reshape(6,)

array([  1,   2,   4, 545,   7,  82])

In [11]:
arr[0]

array([  1,   2,   4, 545,   7,  82])

In [12]:
arr[0][0]

np.int64(1)

In [13]:
arr=np.array([1,2,3,4,5,6])

In [14]:
arr=arr.reshape(2,3)
print(arr)
np.arange(0,7)


[[1 2 3]
 [4 5 6]]


array([0, 1, 2, 3, 4, 5, 6])